services:
  rsbankdb:
    image: bitnami/postgresql:latest
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: rsbank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rsbank"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rsbankms
  account:
    image: rentcontrol/rsbankms-account:v1
    container_name: account
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: 256m
    depends_on:
      rsbankdb:
        condition: service_healthy
    networks:
      - rsbankms
  loan:
    image: rentcontrol/rsbankms-loan:v1
    container_name: loan
    ports:
      - 8081:8081
    deploy:
      resources:
        limits:
          memory: 256m
    depends_on:
      rsbankdb:
        condition: service_healthy
    networks:
      - rsbankms
  card:
    image: rentcontrol/rsbankms-card:v1
    container_name: card
    ports:
      - 8082:8082
    deploy:
      resources:
        limits:
          memory: 256m
    depends_on:
      rsbankdb:
        condition: service_healthy
    networks:
      - rsbankms
networks:
  rsbankms:
    driver: bridge
