server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/rsbank
    username: postgres
    password: root
  jpa:        
    hibernate:
      ddl-auto: create-drop
    show-sql: true
      
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
