server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://rsbankdb:5432/rsbank
    username: postgres
    password: root
  jpa: 
    hibernate:
      ddl-auto: none
    show-sql: true
      
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        
build:
  version: "1.0"

cards:
  message: "Welcome to RSBank cards related docker APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@rsbank.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345