server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/rsbank
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
      
logging:
  level:
    org:
      hibernate:
        sql: DEBUG

build:
  version: "3.0"

loans:
  message: "Welcome to RSBank loan related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@rsbank.com"
  onCallSupport:
    - (555)555-1234
    - (555)523-1345
